import 'package:equatable/equatable.dart';
import 'package:hive/hive.dart'; // Import Hive

part 'post_entity.g.dart'; // This will be generated by hive_generator

@HiveType(typeId: 0) // Assign a unique typeId (e.g., 0)
class PostEntity extends Equatable {
  @HiveField(0) // Assign a unique fieldId (e.g., 0)
  final int userId;

  @HiveField(1) // Assign a unique fieldId (e.g., 1)
  final int id;

  @HiveField(2) // Assign a unique fieldId (e.g., 2)
  final String title;

  @HiveField(3) // Assign a unique fieldId (e.g., 3)
  final String body;

  const PostEntity({
    required this.userId,
    required this.id,
    required this.title,
    required this.body,
  });

  @override
  List<Object?> get props => [userId, id, title, body];
}